global:
  scrape_interval:     30s
  evaluation_interval: 30s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: 
        - balcony:8000
        - stobe:8000
        - raspberrypi:8000
