apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: probes
  namespace: kube-system
spec:
  chart: stable/prometheus
  targetNamespace: default
  valuesContent: |-
    alertmanager:
      enabled: false
    server:
      ingress:
        enabled: true
        hosts:
          - probes.station
      hostAliases:
        - ip: 192.168.178.139
          hostnames:
            - balkon
        - ip: 192.168.178.26
          hostnames:
            - zimmer
        - ip: 192.168.178.18
          hostnames:
            - stobe
    extraScrapeConfigs: |-
      - job_name: probes
        static_configs:
          - targets: 
            - balkon:8000
            - zimmer:8000
            - stobe:8000
